service: edns

provider:
  name: aws
  runtime: python2.7

# you can overwrite defaults here
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:custom.bucket}
            - "/*"

custom:
  bucket: ${self:service}-${self:provider.stage}-storagebucket

functions:
  lookup-vpneast:
    handler: handler.execute
    environment:
      BUCKET_NAME: ${self:custom.bucket}
    events:
      - schedule: rate(2 minutes)

# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
